# Generated by Django 5.2.13 on 2026-09-07 19:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeSetup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('recorded_at', models.DateField(default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_snapshots', to='financeSetup.financialprofile')),
            ],
            options={
                'ordering': ['recorded_at'],
                'unique_together': {('profile', 'recorded_at')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='financeSetup.financialprofile')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['profile', 'date'], name='financeSetu_profile_2ce4e8_idx')],
            },
        ),
    ]
