# Generated by Django 5.2.13 on 2026-05-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tax_identification_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
