# Generated by Django 5.2.13 on 2026-05-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='residential_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
