# Generated by Django 5.2.13 on 2026-05-07 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_residential_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tax_identification_number',
        ),
    ]
